---

- name: firewalld | Create Firewalld zone if does not exist
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone }}"
    state: present
    permanent: true

- name: firewalld | Set Firewalld default zone
  ansible.builtin.shell:
    cmd: |
      firewall-cmd --set-default-zone="{{ firewalld_zone }}"
  when:
    - firewalld_set_default_zone

- name: firewalld | Set Firewalld interface to zone
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone }}"
    interface: "{{ firewalld_interface  }}"
    state: enabled
    permanent: true
    immediate: true
  when:
    - firewalld_set_default_interface

- name: firewalld | Add Firewalld service to zone
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone }}"
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items: "{{ firewalld_services }}"
  notify: Reload Firewalld

- name: firewalld | Add Firewalld ports to zone
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone }}"
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items: "{{ firewalld_ports }}"
  notify: Reload Firewalld
