---

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Include hardware tasks
  ansible.builtin.include_tasks:
    file: hardware.yml

- name: Include distribution specific package tasks
  ansible.builtin.include_tasks: "tasks/{{ ansible_pkg_mgr | lower }}_package.yml"
  when: ansible_distribution is defined

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Include network tasks
  ansible.builtin.include_tasks: "tasks/network.yml"

- name: Include firewall tasks
  ansible.builtin.include_tasks: "tasks/firewall.yml"

- name: Include default tasks
  ansible.builtin.include_tasks:
    file: default.yml

- name: Include default tasks
  ansible.builtin.include_tasks:
    file: cron.yml
