---

- name: Linux distro system update and upgrade for {{ ansible_distribution }}
  action: "{{ ansible_pkg_mgr }} state=latest name='*' update_cache=yes"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: Linux distro system update and upgrade for {{ ansible_distribution }}
  action: "{{ ansible_pkg_mgr }} update_cache=yes cache_valid_time=3600 upgrade=yes autoremove=yes"
  when:
    - ansible_pkg_mgr == "apt"

- name: Linux distro system update and upgrade {{ ansible_distribution }}
  action: "{{ ansible_pkg_mgr }} state=latest name='*' update_cache=yes cache_valid_time=3600 upgrade=yes autoremove=yes"
  when:
    - ansible_pkg_mgr == "pacman"

- name: Install Linux distro prerequisites
  action: "{{ ansible_pkg_mgr }} state=latest update_cache=yes name={{ item }} "
  with_items: "{{ linux_distro_prerequisites }}"

- name: Install Linux distro list of custom packages
  action: "{{ ansible_pkg_mgr }} state=latest update_cache=yes name={{ item }} "
  with_items: "{{ linux_distro_packages }}"
