---

- name: Reboot Server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  vars:
    ansible_host: "{{ ipv4_addresses }}"

- name: Generating Netplan Configuration
  ansible.builtin.command: netplan generate
  become: true
  notify: Applying Netplan Configuration

- name: Applying Netplan Configuration
  ansible.builtin.command: netplan apply
  async: 1
  poll: 0
  become: true
  notify: Reboot Server

- name: Restart Network Manager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  become: true
  notify: Reboot Server

- name: Restart Systemd Networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  become: true
  notify: Reboot Server
