---

#- name: Restart Hostsd
#  ansible.builtin.service:
#    name: hostsd
#    state: restarted
#
#- name: Restart SSHD
#  ansible.builtin.service:
#    name: sshd
#    state: restarted

- name: Reboot Server
  ansible.builtin.reboot:

- name: Generating Netplan Configuration
  ansible.builtin.command: netplan generate
  become: true
  notify:
    - Applying Netplan Configuration

- name: Applying Netplan Configuration
  ansible.builtin.command: netplan apply
  become: true
  notify:
    - Reboot Server

- name: Reload Firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Reload UFW
  ansible.builtin.command: ufw reload
  become: true